dist: trusty
language: python
cache: pip
matrix:
    include:
        - python: 2.7
        - python: 3.5
        - python: 3.6
install:
    - pip install pytest pytest-pep8 pytest-cov

    - pip install -r requirements.txt
script:
  - if [[ "$TEST_MODE" == "PEP8" ]]; then
      PYTHONPATH=$PWD:$PYTHONPATH py.test --pep8 -m pep8;
    else
      PYTHONPATH=$PWD:$PYTHONPATH/tests py.test;
    fi
notifications:
    email: false
